// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSolar.Infrastructure.Persistence;

#nullable disable

namespace SmartSolar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008164645_AddSolarSimulation")]
    partial class AddSolarSimulation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("CustomerType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("customer_type");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.Catalog.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("HeightMm")
                        .HasColumnType("numeric")
                        .HasColumnName("height_mm");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_type");

                    b.Property<decimal?>("RatedPowerW")
                        .HasColumnType("numeric")
                        .HasColumnName("rated_power_w");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("Spec")
                        .HasColumnType("jsonb")
                        .HasColumnName("spec");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WarrantyMonth")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_month");

                    b.Property<decimal?>("WidthMm")
                        .HasColumnType("numeric")
                        .HasColumnName("width_mm");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.AuthActionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("auth_action_token", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("module");

                    b.HasKey("Id");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_file_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.PreSurvey.Entities.PreSurvey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AzimuthDegree")
                        .HasColumnType("numeric")
                        .HasColumnName("azimuth_degree");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GeometryVersion")
                        .HasColumnType("integer")
                        .HasColumnName("geometry_version");

                    b.Property<bool?>("HasObstruction")
                        .HasColumnType("boolean")
                        .HasColumnName("has_obstruction");

                    b.Property<string>("Obstacles")
                        .HasColumnType("jsonb")
                        .HasColumnName("obstacles");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid?>("SelectedSimulationId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_simulation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal?>("SurfaceLengthM")
                        .HasColumnType("numeric")
                        .HasColumnName("surface_length_m");

                    b.Property<decimal?>("SurfaceWidthM")
                        .HasColumnType("numeric")
                        .HasColumnName("surface_width_m");

                    b.Property<decimal?>("TiltDegree")
                        .HasColumnType("numeric")
                        .HasColumnName("tilt_degree");

                    b.Property<decimal?>("TotalAreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("total_area_m2");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("UsableAreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("usable_area_m2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("Id", "SelectedSimulationId");

                    b.ToTable("pre_survey", null, t =>
                        {
                            t.HasCheckConstraint("ck_pre_survey_surface_dimensions_paired", "(surface_length_m IS NULL) = (surface_width_m IS NULL)");

                            t.HasCheckConstraint("ck_pre_survey_versions_non_negative", "geometry_version >= 0 AND revision >= 0");
                        });
                });

            modelBuilder.Entity("SmartSolar.Modules.PreSurvey.Entities.PropertySite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<string>("InstallationSurfaceType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("installation_surface_type");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("StreetLine")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street_line");

                    b.Property<string>("SurfaceMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surface_material");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ward");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("property_site", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.PreSurvey.Entities.SurveyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedSaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_sale_id");

                    b.Property<Guid>("PreSurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pre_survey_id");

                    b.Property<string>("SalesNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("sales_note");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSaleId");

                    b.HasIndex("PreSurveyId")
                        .IsUnique();

                    b.ToTable("survey_request", (string)null);
                });

            modelBuilder.Entity("SmartSolar.Modules.SolarSimulation.Entities.SolarSimulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("algorithm_version");

                    b.Property<decimal?>("AnnualEnergyKwh")
                        .HasColumnType("numeric")
                        .HasColumnName("annual_energy_kwh");

                    b.Property<decimal>("AvailableSurfaceAreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("available_surface_area_m2");

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("climate");

                    b.Property<string>("ClimateStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("climate_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Energy")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("energy");

                    b.Property<string>("EnergyStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("energy_status");

                    b.Property<decimal>("GrossSurfaceAreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_surface_area_m2");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("input_fingerprint")
                        .IsFixedLength();

                    b.Property<decimal>("InstallableAreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("installable_area_m2");

                    b.Property<string>("Installation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("installation");

                    b.Property<decimal>("InstalledCapacityKwp")
                        .HasColumnType("numeric")
                        .HasColumnName("installed_capacity_kwp");

                    b.Property<bool>("IsReusable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reusable");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layout");

                    b.Property<string>("LayoutOrientation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("layout_orientation");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("MountingType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mounting_type");

                    b.Property<decimal>("ObstacleOccupiedAreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("obstacle_occupied_area_m2");

                    b.Property<string>("Obstacles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("obstacles");

                    b.Property<decimal>("PanelAzimuthDegree")
                        .HasColumnType("numeric")
                        .HasColumnName("panel_azimuth_degree");

                    b.Property<int>("PanelCount")
                        .HasColumnType("integer")
                        .HasColumnName("panel_count");

                    b.Property<decimal>("PanelCoveredAreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("panel_covered_area_m2");

                    b.Property<decimal>("PanelTiltDegree")
                        .HasColumnType("numeric")
                        .HasColumnName("panel_tilt_degree");

                    b.Property<int>("PreSurveyGeometryVersion")
                        .HasColumnType("integer")
                        .HasColumnName("pre_survey_geometry_version");

                    b.Property<Guid>("PreSurveyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pre_survey_id");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_brand");

                    b.Property<decimal>("ProductHeightMm")
                        .HasColumnType("numeric")
                        .HasColumnName("product_height_mm");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductInstallationSpec")
                        .HasColumnType("jsonb")
                        .HasColumnName("product_installation_spec");

                    b.Property<string>("ProductModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_model");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("ProductRatedPowerW")
                        .HasColumnType("numeric")
                        .HasColumnName("product_rated_power_w");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_sku");

                    b.Property<decimal>("ProductWidthMm")
                        .HasColumnType("numeric")
                        .HasColumnName("product_width_mm");

                    b.Property<decimal?>("SpecificYieldKwhPerKwpYear")
                        .HasColumnType("numeric")
                        .HasColumnName("specific_yield_kwh_per_kwp_year");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("SurfaceAzimuthDegree")
                        .HasColumnType("numeric")
                        .HasColumnName("surface_azimuth_degree");

                    b.Property<decimal>("SurfaceLengthM")
                        .HasColumnType("numeric")
                        .HasColumnName("surface_length_m");

                    b.Property<decimal>("SurfaceTiltDegree")
                        .HasColumnType("numeric")
                        .HasColumnName("surface_tilt_degree");

                    b.Property<decimal>("SurfaceWidthM")
                        .HasColumnType("numeric")
                        .HasColumnName("surface_width_m");

                    b.Property<decimal>("TotalModuleAreaM2")
                        .HasColumnType("numeric")
                        .HasColumnName("total_module_area_m2");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings");

                    b.HasKey("Id");

                    b.HasAlternateKey("PreSurveyId", "Id")
                        .HasName("ak_solar_simulation_pre_survey_id_id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PreSurveyId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_solar_simulation_pre_survey_id_created_at");

                    b.HasIndex("PreSurveyId", "InputFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_solar_simulation_reusable_fingerprint")
                        .HasFilter("\"is_reusable\"");

                    b.ToTable("solar_simulation", null, t =>
                        {
                            t.HasCheckConstraint("ck_solar_simulation_climate_status", "climate_status IN ('SUCCEEDED', 'UNAVAILABLE', 'FAILED')");

                            t.HasCheckConstraint("ck_solar_simulation_energy_status", "energy_status IN ('SUCCEEDED', 'NOT_APPLICABLE', 'UNAVAILABLE', 'FAILED')");

                            t.HasCheckConstraint("ck_solar_simulation_geometry_version_non_negative", "pre_survey_geometry_version >= 0");

                            t.HasCheckConstraint("ck_solar_simulation_mounting_type", "mounting_type IN ('FLUSH', 'RACK')");

                            t.HasCheckConstraint("ck_solar_simulation_panel_count_non_negative", "panel_count >= 0");

                            t.HasCheckConstraint("ck_solar_simulation_status", "status IN ('COMPLETED', 'PARTIALLY_COMPLETED')");
                        });
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.HasOne("SmartSolar.Modules.Identity.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.AuthActionToken", b =>
                {
                    b.HasOne("SmartSolar.Modules.Identity.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartSolar.Modules.Identity.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.RolePermission", b =>
                {
                    b.HasOne("SmartSolar.Modules.Identity.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSolar.Modules.Identity.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.UserRole", b =>
                {
                    b.HasOne("SmartSolar.Modules.Identity.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSolar.Modules.Identity.Entities.UserAccount", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartSolar.Modules.PreSurvey.Entities.PreSurvey", b =>
                {
                    b.HasOne("SmartSolar.Modules.PreSurvey.Entities.PropertySite", "Property")
                        .WithMany("PreSurveys")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSolar.Modules.SolarSimulation.Entities.SolarSimulation", null)
                        .WithMany()
                        .HasForeignKey("Id", "SelectedSimulationId")
                        .HasPrincipalKey("PreSurveyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pre_survey_selected_simulation_same_pre_survey");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SmartSolar.Modules.PreSurvey.Entities.PropertySite", b =>
                {
                    b.HasOne("Customer", "Customer")
                        .WithMany("PropertySites")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SmartSolar.Modules.PreSurvey.Entities.SurveyRequest", b =>
                {
                    b.HasOne("SmartSolar.Modules.Identity.Entities.UserAccount", "AssignedSale")
                        .WithMany()
                        .HasForeignKey("AssignedSaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartSolar.Modules.PreSurvey.Entities.PreSurvey", "PreSurvey")
                        .WithOne("SurveyRequest")
                        .HasForeignKey("SmartSolar.Modules.PreSurvey.Entities.SurveyRequest", "PreSurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedSale");

                    b.Navigation("PreSurvey");
                });

            modelBuilder.Entity("SmartSolar.Modules.SolarSimulation.Entities.SolarSimulation", b =>
                {
                    b.HasOne("SmartSolar.Modules.Identity.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSolar.Modules.PreSurvey.Entities.PreSurvey", null)
                        .WithMany()
                        .HasForeignKey("PreSurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSolar.Modules.Catalog.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.Navigation("PropertySites");
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartSolar.Modules.Identity.Entities.UserAccount", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartSolar.Modules.PreSurvey.Entities.PreSurvey", b =>
                {
                    b.Navigation("SurveyRequest");
                });

            modelBuilder.Entity("SmartSolar.Modules.PreSurvey.Entities.PropertySite", b =>
                {
                    b.Navigation("PreSurveys");
                });
#pragma warning restore 612, 618
        }
    }
}
